version: '3.8'

services:
  web:
    image: nginx:1.23.3
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "8081:80"
    depends_on:
      - app
    container_name: fruits_nginx

  app:
    build:
      context: .
      dockerfile: ./_docker/app/Dockerfile
    volumes:
      - ./:/var/www
    container_name: fruits_app

##postgresql
#  db:
#    build:
#      context: .
#      dockerfile: ./_docker/postgresql/Dockerfile
#    environment:
#      POSTGRES_DB: "fr"
#      POSTGRES_USER: "root"
#      POSTGRES_PASSWORD: "root"
#      PGDATA: "/var/lib/postgresql/data/pgdata"
#    volumes:
#      - ../2. Init Database:/docker-entrypoint-initdb.d
#      - .:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"